In [1]:
%load_ext autoreload
%autoreload 2

import gym
import numpy as np
import random
from collections import namedtuple, deque



import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

import datetime
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from QNetworks import QNetwork1
from ReplayBuffer import ReplayBuffer
from Agents import *
from DQN_Algorithms import dqn_acrobot

In [3]:
env = gym.make('Acrobot-v1')
env.seed(0)

state_shape = env.observation_space.shape[0]
action_shape = env.action_space.n

print('State shape: ', state_shape)
print('Action shape: ', action_shape)

State shape:  6
Action shape:  3


In [4]:
def dqn(n_episodes=10000, max_t=1000, eps_start=1.0, eps_end=0.01, eps_decay=0.995):
    """Deep Q-Learning.
    
    Params
    ======
        n_episodes (int): maximum number of training episodes
        max_t (int): maximum number of timesteps per episode
        eps_start (float): starting value of epsilon, for epsilon-greedy action selection
        eps_end (float): minimum value of epsilon
        eps_decay (float): multiplicative factor (per episode) for decreasing epsilon
    """
    scores = []                 # list containing scores from each episode
    scores_window_printing = deque(maxlen=10) # For printing in the graph
    scores_window= deque(maxlen=100)  # last 100 scores for checking if the avg is more than 195
    eps = eps_start                    # initialize epsilon
    for i_episode in range(1, n_episodes+1):
        state = env.reset()
        score = 0
        for t in range(max_t):
            action = agent.act(state, eps)
            next_state, reward, done, _ = env.step(action)
            agent.step(state, action, reward, next_state, done)
            state = next_state
            score += reward
            if done:
                break 
        scores_window.append(score)       # save most recent score
        scores_window_printing.append(score)              # save most recent score
        eps = max(eps_end, eps_decay*eps) # decrease epsilon
        print('\rEpisode {}\tAverage Score: {:.2f}'.format(i_episode, np.mean(scores_window)), end="")  
        if i_episode % 10 == 0: 
            scores.append(np.mean(scores_window_printing))        
        if i_episode % 100 == 0: 
            print('\rEpisode {}\tAverage Score: {:.2f}'.format(i_episode, np.mean(scores_window)))
        if np.mean(scores_window)>=-80.0:
            print('\nEnvironment solved in {:d} episodes!\tAverage Score: {:.2f}'.format(i_episode-100, np.mean(scores_window)))
            break
    return [np.array(scores),i_episode-100]

In [ ]:

    
no_siblings5 = 1
sibling_scores5 = []
sibling_lives5 = np.zeros(no_siblings5)

begin_time5 = datetime.datetime.now()
for i in range(no_siblings5):
    
    agent = Agent5(state_size=state_shape,action_size = action_shape,seed = 0)
    [temp_scores,sibling_lives5[i]] = dqn()
    sibling_scores5.append(temp_scores)
    
no_siblings6 = 1
sibling_scores6 = []
sibling_lives6 = np.zeros(no_siblings6)

begin_time6 = datetime.datetime.now()
for i in range(no_siblings6):
    
    agent = Agent6(state_size=state_shape,action_size = action_shape,seed = 0)
    [temp_scores,sibling_lives6[i]] = dqn()
    sibling_scores6.append(temp_scores)
    
no_siblings7 = 1
sibling_scores7 = []
sibling_lives7 = np.zeros(no_siblings7)

begin_time7 = datetime.datetime.now()
for i in range(no_siblings7):
    
    agent = Agent7(state_size=state_shape,action_size = action_shape,seed = 0)
    [temp_scores,sibling_lives7[i]] = dqn()
    sibling_scores7.append(temp_scores)
    
no_siblings8 = 1
sibling_scores8 = []
sibling_lives8 = np.zeros(no_siblings4)

begin_time4 = datetime.datetime.now()
for i in range(no_siblings8):
    
    agent = Agent8(state_size=state_shape,action_size = action_shape,seed = 0)
    [temp_scores,sibling_lives8[i]] = dqn()
    sibling_scores8.append(temp_scores)

Episode 100	Average Score: -401.22
Episode 200	Average Score: -186.23
Episode 300	Average Score: -142.63
Episode 400	Average Score: -118.48
Episode 500	Average Score: -114.34
Episode 600	Average Score: -108.98
Episode 700	Average Score: -105.04
Episode 800	Average Score: -104.44
Episode 900	Average Score: -100.58
Episode 1000	Average Score: -99.21
Episode 1100	Average Score: -105.10
Episode 1200	Average Score: -100.83
Episode 1300	Average Score: -100.25
Episode 1400	Average Score: -96.062
Episode 1500	Average Score: -97.40
Episode 1600	Average Score: -96.79
Episode 1700	Average Score: -93.69
Episode 1800	Average Score: -93.75
Episode 1900	Average Score: -102.57
Episode 2000	Average Score: -103.95
Episode 2100	Average Score: -96.488
Episode 2200	Average Score: -95.09
Episode 2300	Average Score: -95.23
Episode 2400	Average Score: -91.73
Episode 2500	Average Score: -95.66
Episode 2600	Average Score: -91.61
Episode 2700	Average Score: -94.57
Episode 2800	Average Score: -90.26
Episode 2900	

In [6]:
a = torch.rand(2,3)
print(a)
print(a.max(1)[0].unsqueeze(1))

tensor([[0.3303, 0.8665, 0.1212],
        [0.4020, 0.3005, 0.8721]])
tensor([[0.8665],
        [0.8721]])


In [7]:
from QNetworks import QNetwork1
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
myNetwork = QNetwork1(3,2,0).to(device)

In [14]:
b = np.array([1.0,2.0,3.0,4.0,5.0,6.0])
print(b)
b = torch.from_numpy(b).float().unsqueeze(0).to(device)
print(b)

[1. 2. 3. 4. 5. 6.]
tensor([[1., 2., 3., 4., 5., 6.]], device='cuda:0')


In [9]:

print(myNetwork(b).detach().max(1)[0].unsqueeze(1))

tensor([[0.3096]], device='cuda:0')


In [17]:
experiences1 = np.random.rand(10,3)
print(experiences1)

[[0.59763217 0.29764736 0.02443431]
 [0.93420254 0.2968834  0.0448549 ]
 [0.80191385 0.56115691 0.75301579]
 [0.29965167 0.7396202  0.88320427]
 [0.93918335 0.48557929 0.02016853]
 [0.80376276 0.3885355  0.2136312 ]
 [0.04214878 0.47487267 0.24353678]
 [0.25737305 0.27221931 0.75448379]
 [0.10761848 0.85141035 0.22594016]
 [0.81420701 0.79866703 0.02299499]]


In [20]:
experiences1 = np.random.rand(10,3)
states1 = torch.from_numpy(np.vstack([e for e in experiences1 if e is not None])).float().to(device)
print(states1)

experiences2 = np.random.rand(10,3)
states2 = torch.from_numpy(np.vstack([e for e in experiences2 if e is not None])).float().to(device)
print(states2)

tensor([[0.5770, 0.4560, 0.5029],
        [0.3156, 0.6510, 0.9008],
        [0.8389, 0.7519, 0.7526],
        [0.8823, 0.7111, 0.1753],
        [0.8260, 0.4738, 0.5264],
        [0.6019, 0.1371, 0.9816],
        [0.3569, 0.3338, 0.0744],
        [0.9041, 0.9731, 0.0608],
        [0.7011, 0.6813, 0.6678],
        [0.5494, 0.6704, 0.5797]], device='cuda:0')
tensor([[0.0397, 0.6178, 0.7907],
        [0.7246, 0.5015, 0.3224],
        [0.7746, 0.1702, 0.2958],
        [0.1349, 0.7963, 0.4098],
        [0.6295, 0.9349, 0.3768],
        [0.4827, 0.4871, 0.4768],
        [0.8459, 0.1922, 0.9849],
        [0.7778, 0.1209, 0.1090],
        [0.1273, 0.0706, 0.1182],
        [0.5836, 0.4598, 0.2176]], device='cuda:0')


In [15]:
print(env.reset())

[ 0.99612767 -0.08791855  0.99998543  0.00539742 -0.09194186  0.09558882]


In [26]:
print(myNetwork(states1).detach().max(1)[0].unsqueeze(1))
tempstates1 = myNetwork(states1).detach().max(1)[0].unsqueeze(1)
print(myNetwork(states2).detach().max(1)[0].unsqueeze(1))
tempstates2 = myNetwork(states2).detach().max(1)[0].unsqueeze(1)

tensor([[0.1065],
        [0.1336],
        [0.1261],
        [0.0946],
        [0.1027],
        [0.1209],
        [0.0700],
        [0.1024],
        [0.1209],
        [0.1184]], device='cuda:0')
tensor([[0.1220],
        [0.0977],
        [0.0751],
        [0.1146],
        [0.1154],
        [0.1082],
        [0.1085],
        [0.0573],
        [0.0663],
        [0.0904]], device='cuda:0')


In [27]:
loss = F.mse_loss(tempstates1, tempstates2)
print(loss)

tensor(0.0012, device='cuda:0')


In [30]:
import torch.optim as optim  
optimizer = optim.Adam(myNetwork.parameters(), lr=0.005)


In [31]:
optimizer.zero_grad()
print(optimizer.zero_grad())
loss.backward()
print(loss.backward())

None


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
a = 2.45
print(a)
print(type(a))
b = torch.Tensor(np.array(a))

In [ ]:
a = True
print(np.vstack([a]))

In [3]:
import hickle as hkl

a,b,c = hkl.load('Data_Case1')

In [4]:
print(a)
print(b)
print(c)

[737.]
[array([-500. , -500. , -500. , -467. , -459.9, -427.7, -357.9, -285.6,
       -256.1, -251.6, -260.3, -219.3, -186.1, -222.8, -171.2, -192.7,
       -132.9, -139.5, -162.1, -170.9, -141.3, -138.2, -119.2, -126.9,
       -118.1, -113.5, -112.2, -104.2,  -97.5, -108.7, -112.6, -100.6,
        -91.8, -104.8,  -90.7,  -93.1, -101.1, -103.9,  -96.2,  -94.8,
       -110.7,  -90.1, -130.2,  -95.6,  -93.3,  -87.9,  -83. ,  -87.2,
        -85.5,  -85.2,  -85.2,  -85.2,  -84.4,  -83.8,  -83.1,  -77.4,
        -89.5,  -86.5, -102.7,  -80.3,  -84.7,  -85.8,  -87. ,  -84.3,
        -73.6,  -74.1,  -76.4, -103.5,  -79.3,  -89.8,  -78.8,  -77. ,
        -82.9,  -88.2,  -80. ,  -80. ,  -80.3,  -84.5,  -75. ,  -77.5,
        -83.4,  -83.2,  -77.4])]
0:06:46.151717
